- name: install acl
  package:
    name: acl
    state: present

- name: create the root dir
  file:
    state: directory
    dest: "{{ git_repositories_root_dir }}"
    owner: "{{ git_repositories_user }}"
    group: "{{ git_repositories_group }}"
    mode: 0755

  # NOTE(vincent): can't use the git module to do this !

- name: create the repositories # noqa command-instead-of-module
  become: yes
  become_user: "{{ git_repositories_user }}"
  command: git init --bare "{{ git_repositories_root_dir }}/{{ item }}"
  args:
    creates: "{{ git_repositories_root_dir }}/{{ item }}"
  with_items: "{{ git_repositories }}"

- name: chown the repositories
  file:
    dest: "{{ git_repositories_root_dir }}"
    owner: "{{ git_repositories_user }}"
    group: "{{ git_repositories_group }}"
    recurse: yes
